name: CI

# Trigger the workflow on every push and pull request to the main branch
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    # Test on two different recent versions of Python
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install build tools
      run: |
        pip install build

    - name: Install package with dev dependencies
      run: |
        pip install -e .[dev]  # Installs the package with "dev" extras including pytest

    - name: Build the package
      run: |
        python -m build

    - name: Run tests
      run: |
        pytest